### ISSUE TITLE
error[E0425]: cannot find function `get_internal` in this scope when compiling to WASM

### ISSUE THREAD

**Issue by UnHumbleBen** [ruuda/thread-id#10]
Error message reads:
```
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling thread-id v3.3.0
   Compiling backtrace-sys v0.1.31
   Compiling backtrace v0.3.34
error[E0425]: cannot find function `get_internal` in this scope
  --> /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/thread-id-3.3.0/src/lib.rs:44:5
   |
44 |     get_internal()
   |     ^^^^^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `thread-id`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
```

**Comment by ruuda** [comment]
Is there a way to detect webassembly with a `#[cfg]` attribute? Currently we support `cfg(unix)`, `cfg(windows)` and `cfg(target_os = "redox")`.

**Comment by UnHumbleBen** [comment]
I am still fairly new to Rust, so I am not that familiar with conditional compilation. It seems like you can detect web assembly with `#[cfg(target_arch = "wasm32")]`. That being said, based on the docs, it seems that [spawning threads is not possible yet.](https://rustwasm.github.io/docs/book/reference/add-wasm-support-to-crate.html#avoid-spawning-threads)

**Comment by ruuda** [comment]
> That being said, based on the docs, it seems that spawning threads is not possible yet.

In that case, we could easily add wasm support, and make it always return 0 as the current thread id. But given that there are plans to add threading in the future, that will break as soon as threads are added. And instead of failing loudly, all code relying on `thread_id::get` would be subtly broken.

From what I gather [here](https://developers.google.com/web/updates/2018/10/wasm-threads) it looks like wasm will expose a pthread compatible API. So we could also try to extend the `cfg(unix)` config to wasm. The `libc` crate [provides `pthread_self` for wasm32-unknown-emscripten](https://rust-lang.github.io/libc/wasm32-unknown-emscripten/libc/index.html), but [not for wasm32-unknown-unknown](https://rust-lang.github.io/libc/wasm32-unknown-unknown/libc/index.html). And for emscripten, `pthread_self` returns a constant (see #4).

So I don’t see a solution that is clearly the right one. If threads are not yet supported in wasm anyway, perhaps your best bet is to disable the code that relies on `thread_id::get()` for wasm.

**Comment by daxpedda** [comment]
It is possible to spawn thread in Wasm with `target_feature = "atomic"`, see [the `wasm-bindgen` guide](https://rustwasm.github.io/docs/wasm-bindgen/examples/raytrace.html).

This is specifically for `wasm32-unknown-unknown` and not for Emscripten or WASI. Emscripten has it's own interface through pthreads (which works in the browser with a shim) that has an actual thread ID. WASI doesn't support threads until `wasm32-wasi-threads` is implemented.

Would a PR be acceptable that uses an atomic counter to implement thread IDs until there is a different solution available for `wasm32-unknown-unknown`?

As far as I'm aware, there is currently no proposal for `wasm32-unknown-unknown` to add any thread spawning capability. JS also doesn't offer any thread ID equivalent.

**Comment by ruuda** [comment]
> uses an atomic counter to implement thread IDs

How would that work? I suppose you don’t intend to return a different id every time the function is called, is there something like thread-local storage available?

**Comment by daxpedda** [comment]
Yes, Rusts `thread_local!` macro works.

**Comment by daxpedda** [comment]
I made #12 with an atomic counter, as proposed.

**Comment by ruuda** [comment]
This is now resolved for `wasm32-unknown-unknown` in [version 4.1.0](https://crates.io/crates/thread-id/4.1.0), thanks to @daxpedda!

As for WASI, [it looks like threads are still not supported there](https://github.com/WebAssembly/wasi-threads), so for anybody who runs into this, the best solution is probably to avoid the call to `thread_id::get()` altogether with a `#[cfg]` attribute, if your code is able to work without threads.
